language: cpp
compiler:
  - gcc
  - clang
env:
  - PROJECT=NAMICExternalProjects cmake_package=cmake-2.8.12.2
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq phonon-backend-gstreamer
  - sudo apt-get install -qq qt-sdk
  - cd $TRAVIS_BUILD_DIR/..
  - wget http://www.cmake.org/files/v2.8/$cmake_package.tar.gz -v -O $cmake_package.tar.gz
  - tar -xzvf $cmake_package.tar.gz
  - cd $cmake_package
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_USE_OPENSSL:BOOL=ON && sudo make install
before_script:
  - cd $TRAVIS_BUILD_DIR/..
# Change this to your needs
script:
  - mkdir ${PROJECT}-build && cd ${PROJECT}-build
  - cmake -DBUILD_ITKTransformTools:BOOL=ON $TRAVIS_BUILD_DIR
  - make
